#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'dl-package','console_scripts','dl_node'
__requires__ = 'dl-package'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('dl-package', 'console_scripts', 'dl_node')()
    )
